export const ActionTypes = {
    GET_PRODUCTS: {
        GET_PRODUCTS_FETCH_DATA: "GET_PRODUCTS_FETCH_DATA",
        GET_PRODUCTS_FETCH_DATA_SUCCESS: "GET_PRODUCTS_FETCH_DATA_SUCCESS",

        GET_PRODUCT_BY_CATEGORY_DATA_SUCCESS: "GET_PRODUCT_BY_CATEGORY_DATA_SUCCESS",
        GET_PRODUCT_BY_CATEGORY_DATA: "GET_PRODUCT_BY_CATEGORY_DATA",

        GET_SINGLE_PRODUCT_DATA_SUCCESS: "GET_SINGLE_PRODUCT_DATA_SUCCESS",
        GET_SINGLE_PRODUCT_DATA: "GET_SINGLE_PRODUCT_DATA",

        SORT_PRODUCT_PRICE_SUCCESS: "SORT_PRODUCT_PRICE_SUCCESS",
        SORT_PRODUCT_PRICE: "SORT_PRODUCT_PRICE",

        SET_PRODUCT_QUANTITY: "SET_PRODUCT_QUANTITY",    
        SET_CART_QUANTITY: "SET_CART_QUANTITY",
        SET_MENUBAR_STATUS: "SET_MENUBAR_STATUS",
        SET_TOTAL_PRICE_STATUS: "SET_TOTAL_PRICE_STATUS",
    }
}